### ISSUE TITLE
Typo in OpenAssetIO logo file used in the examples

### ISSUE THREAD

**Issue by mjtitchener-fn** [OpenAssetIO/OpenAssetIO-MediaCreation#85]
Hello,

Very minor thing but I noticed that the logo files used in the examples have a typo.

![logo](https://github.com/OpenAssetIO/OpenAssetIO-MediaCreation/assets/72390925/7dbbe478-21cf-42ae-9ca6-960dc83273ad)

examples/resources/hello_openassetio/logo.jpg
examples/resources/querying_entity_versions/logo.jpg

Thanks,
Mark

**Comment by feltech** [comment]
:grin: Good spot. This was deliberate for usage in the "querying_entity_versions" notebook, which tells a story of having a misspelled logo that needs to be corrected by publishing a new version.

The other notebooks then reused the same image, accidentally copy-pasting the deliberately-wrong one instead of the corrected one :facepalm:

**Comment by mjtitchener-fn** [comment]
It did cross my mind if this was deliberate but I'll admit I didn't look beyond the image and dig into the notebooks myself.
